version: '3.8'
services:
  backend:
    build: ./backend
    ports: ['4000:4000']
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports: ['3000:3000']
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:4000
